// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BAVCL.Tests.Features.Vectors
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class VectorInitialisationFeature : object, Xunit.IClassFixture<VectorInitialisationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "vector_creation.feature"
#line hidden
        
        public VectorInitialisationFeature(VectorInitialisationFeature.FixtureData fixtureData, BAVCL_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Vectors", "Vector Initialisation", "    Vector creation.\r\n    Can create cached and non-cached vectors. Values saved " +
                    "to both RAM & GRAM\r\n    Can create empty vector of given length that is always c" +
                    "ached. Values only saved to GRAM.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
    #line hidden
#line 8
        testRunner.Given("I have a gpu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cached Vector Creation")]
        [Xunit.TraitAttribute("FeatureTitle", "Vector Initialisation")]
        [Xunit.TraitAttribute("Description", "Cached Vector Creation")]
        public virtual void CachedVectorCreation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cached Vector Creation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Value"});
                table5.AddRow(new string[] {
                            "NaN"});
                table5.AddRow(new string[] {
                            "Inf"});
                table5.AddRow(new string[] {
                            "-Inf"});
                table5.AddRow(new string[] {
                            "5.0"});
                table5.AddRow(new string[] {
                            "0.1234"});
                table5.AddRow(new string[] {
                            "-0.2434"});
#line 11
        testRunner.When("I create the following cached vector", ((string)(null)), table5, "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Columns",
                            "0"});
                table6.AddRow(new string[] {
                            "Rows",
                            "1"});
                table6.AddRow(new string[] {
                            "Length",
                            "6"});
                table6.AddRow(new string[] {
                            "LiveCount",
                            "0"});
                table6.AddRow(new string[] {
                            "MemorySize",
                            "24"});
#line 19
        testRunner.Then("the vector should have the following properties", ((string)(null)), table6, "Then ");
#line hidden
#line 25
        testRunner.And("it should be cached on the GPU", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
        testRunner.And("there should be 1 item stored on the GPU", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Value"});
                table7.AddRow(new string[] {
                            "NaN"});
                table7.AddRow(new string[] {
                            "Inf"});
                table7.AddRow(new string[] {
                            "-Inf"});
                table7.AddRow(new string[] {
                            "5.0"});
                table7.AddRow(new string[] {
                            "0.1234"});
                table7.AddRow(new string[] {
                            "-0.2434"});
#line 27
        testRunner.And("the vector should have the following values on the CPU and GPU", ((string)(null)), table7, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Non-cached Vector Creation")]
        [Xunit.TraitAttribute("FeatureTitle", "Vector Initialisation")]
        [Xunit.TraitAttribute("Description", "Non-cached Vector Creation")]
        public virtual void Non_CachedVectorCreation()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Non-cached Vector Creation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 36
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Value"});
                table8.AddRow(new string[] {
                            "NaN"});
                table8.AddRow(new string[] {
                            "Inf"});
                table8.AddRow(new string[] {
                            "-Inf"});
                table8.AddRow(new string[] {
                            "5.0"});
                table8.AddRow(new string[] {
                            "0.1234"});
                table8.AddRow(new string[] {
                            "-0.2434"});
#line 37
        testRunner.When("I create the following non-cached vector", ((string)(null)), table8, "When ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Columns",
                            "0"});
                table9.AddRow(new string[] {
                            "Rows",
                            "1"});
                table9.AddRow(new string[] {
                            "Length",
                            "6"});
                table9.AddRow(new string[] {
                            "LiveCount",
                            "0"});
                table9.AddRow(new string[] {
                            "MemorySize",
                            "24"});
#line 45
        testRunner.Then("the vector should have the following properties", ((string)(null)), table9, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Value"});
                table10.AddRow(new string[] {
                            "NaN"});
                table10.AddRow(new string[] {
                            "Inf"});
                table10.AddRow(new string[] {
                            "-Inf"});
                table10.AddRow(new string[] {
                            "5.0"});
                table10.AddRow(new string[] {
                            "0.1234"});
                table10.AddRow(new string[] {
                            "-0.2434"});
#line 51
        testRunner.And("the vector should have the following values on the CPU", ((string)(null)), table10, "And ");
#line hidden
#line 59
        testRunner.And("it should not be cached on the GPU", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create An Empty Vector Of Given Length")]
        [Xunit.TraitAttribute("FeatureTitle", "Vector Initialisation")]
        [Xunit.TraitAttribute("Description", "Create An Empty Vector Of Given Length")]
        public virtual void CreateAnEmptyVectorOfGivenLength()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create An Empty Vector Of Given Length", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 61
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    this.FeatureBackground();
#line hidden
#line 62
        testRunner.When("I create a zeros vector of length 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Columns",
                            "0"});
                table11.AddRow(new string[] {
                            "Rows",
                            "1"});
                table11.AddRow(new string[] {
                            "Length",
                            "5"});
                table11.AddRow(new string[] {
                            "LiveCount",
                            "0"});
                table11.AddRow(new string[] {
                            "MemorySize",
                            "20"});
#line 63
        testRunner.Then("the vector should have the following properties", ((string)(null)), table11, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Value"});
                table12.AddRow(new string[] {
                            "0"});
                table12.AddRow(new string[] {
                            "0"});
                table12.AddRow(new string[] {
                            "0"});
                table12.AddRow(new string[] {
                            "0"});
                table12.AddRow(new string[] {
                            "0"});
#line 69
        testRunner.And("the vector should have the following values on the CPU", ((string)(null)), table12, "And ");
#line hidden
#line 76
        testRunner.And("it should be cached on the GPU", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                VectorInitialisationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                VectorInitialisationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
